#!/usr/bin/expect -f

set timeout 30
set host "187.127.154.55"
set user "aqil"
set pass "aqil@noon"
set pubkey "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxPce4jyOy7fbFz0Kiv9dM3MoN4xgrkGfXMHU3vIUZNENBdU5EnXui2mDyAJG6v7TBU3QWcCG81V8dg1gkcCQhKv+f6a9nz6bxdWud1x7Hs2Nyuk2wfVKxwLOZRDp7EpAfI93HlHeqQeREMG68R/nJfJpUtSQgEsUsh1lUVAb4AY/91Vbnmtxj5L+uxGfPycsTs5qayTIuuL18EjQI7/cv8zMV1Z6nwYY0b4Jjmdo8SiX9GhpwISEEejMG0mtgrNaIof1q2haq73l+yHhRtQn/BTsp6ULF7A6bB20XgoFJ9IexIhfLAw1Z0Fg9NYTSR5CcCfNrKvF1KQoZUJB+VS/xxx2SWUQ92B2+EW2P062TNPZY05Z7yYgzyqctwrMie1n8rC1Pk19EsVe3qVbP3XkSnJs7IfekGdOAZiGHFx05e7J3Dlk4od9Q2xuXTMDlr6pCrFMu93MvoVcsSvxSDUzsJgfyLL+B27EAYfi0i2cnIKEDfO0G7HsyG0LZxR8jVgMPs+8dlTLghUw0zsjTy4WSoxgOq6DQWFrY5miAoGo4DxrSojE9Lixsnha8B3FcPVg3FMNqcRcsukifI25Zu7A8VLLSjHTG2hxu1WSOjrwmXEqhjzDKUGHiNsnyDgAejY66cSJLFChTJL2uFFt8cK2mZzEYt2hXJ8pG4bM0nlLsAQ== aqilali381@gmail.com"

spawn ssh -o StrictHostKeyChecking=no $user@$host

expect {
    "password:" {
        send "$pass\r"
    }
}

expect -re ".*"
send "mkdir -p ~/.ssh && echo '$pubkey' >> ~/.ssh/authorized_keys && chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys\r"
expect -re ".*"
send "exit\r"
expect eof
