#!/usr/bin/expect -f

set timeout 30
set host "187.127.154.55"
set user "aqil"
set pass "aqil@noon"

spawn ssh -o StrictHostKeyChecking=no $user@$host

expect {
    "password:" {
        send "$pass\r"
    }
}

expect "aqil@"
sleep 1
send "sudo strings /proc/$(pgrep node | head -n 1)/environ | grep ENCRYPTION_KEY\r"
expect {
    "password" {
        send "$pass\r"
        exp_continue
    }
    "aqil@"
}
send "exit\r"
expect eof
