#!/usr/bin/expect -f

set timeout 30
set host "187.127.154.55"
set user "aqil"
set pass "aqil@noon"
set cmd [lindex $argv 0]

spawn ssh -o StrictHostKeyChecking=no $user@$host

expect {
    "password:" {
        send "$pass\r"
    }
}

expect -re ".*\[$#\] "
send "$cmd\r"
expect {
    "Password:" {
        send "$pass\r"
        exp_continue
    }
}

expect -re ".*\[$#\] "
send "exit\r"
expect eof
